apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ include "image" .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ default 9090 .Values.containerPort }}
              name: default
          volumeMounts:
            - name: prometheus-config
              mountPath: "/etc/prometheus"
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus
