{{- $podName := "prometheus-operator" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $podName }}
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
  labels:
    app: {{ $podName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $podName }}
  template:
    metadata:
      labels:
        app: {{ $podName }}
    spec:
      containers:
        - name: {{ $podName }}
          image: {{ include "image" .Values.image }}
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 9090
              name: default
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      serviceAccountName: {{ $podName }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-from-prometheus-operator
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ $podName }}
  policyTypes:
    - Egress
  egress:
    - {}  # Allows all egress traffic to any destination and port
