{{- if default dict .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
  annotations:
    {{- range $annotation, $value := default dict .Values.ingress.annotations }}
    {{ $annotation }}: {{ $value }}
    {{- end }}
spec:
  ingressClassName: {{ default "nginx" .Values.ingress.class }}
  rules:
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-operated
                port:
                  number: 9090
  {{- end }}
  tls:
    - hosts:
      {{- range $host := .Values.ingress.hosts }}
        - "{{ $host }}"
      {{- end }}
      secretName: prometheus-tls
{{- end }}
