apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      app: prometheus
  image: {{ include "image" .Values.prometheus.image }}
  version: {{ .Values.prometheus.image.tag }}
  initContainers:
  - name: config-reloader
    image: {{ include "image" .Values.prometheus-config-reloader.image }}
