apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  labels:
    app: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 9090
    name: default
  selector:
    app: prometheus-operator
