apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: delivery-service
  endpoints:
    - port: default
      interval: {{ default "15s" .Values.scrapeInterval }}
