apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  namespace: {{ .Values.target_namespace | default .Release.Namespace }}
  labels:
    app: prometheus-operator
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 9090
    name: default
  selector:
    app: prometheus-operator
