name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    permissions:
      contents: read
    with:
      mode: ${{ inputs.mode }}

  helmcharts:
    name: Build Helmcharts
    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@master
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      name: prometheus-operator
      dir: charts/prometheus-operator
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: charts/odg
      ocm-mappings: |
        - ref: ocm-resource:prometheus-operator.repository
          attribute: image.repository
        - ref: ocm-resource:prometheus-operator.tag
          attribute: image.tag
        - ref: ocm-resource:prometheus.repository
          attribute: prometheus.image.repository
        - ref: ocm-resource:prometheus.tag
          attribute: prometheus.image.tag
        - ref: ocm-resource:prometheus-config-reloader.repository
          attribute: prometheus-config-reloader.image.repository
        - ref: ocm-resource:prometheus-config-reloader.tag
          attribute: prometheus-config-reloader.image.tag
