name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    permissions:
      contents: read
    with:
      mode: ${{ inputs.mode }}

  odg-extension-definitions:
    runs-on: ubuntu-latest
    needs:
    - prepare
    steps:
    - uses: actions/checkout@v4
    - name: Export odg-extension-definitions
      run: |
        export version=${{ needs.prepare.outputs.version }}
        blobs_dir=blobs.d
        mkdir $blobs_dir
        extension_definitions="extension-definitions.yaml"

        yq -i '
          .installation.ocm_references[].version = strenv(version) |
          .installation.ocm_references[].artefact.version = strenv(version) |
          .installation.ocm_references[].mappings[].version = strenv(version)
        ' ${extension_definitions}

        tar czf ${blobs_dir}/extension_definitions.tar.gz ${extension_definitions}

    - uses: gardener/cc-utils/.github/actions/export-ocm-fragments@master
      with:
        ocm-resources: |
          name: odg-extension-definitions
          type: odg-extension
          relation: local
          access:
            type: localBlob
            localReference: extension_definitions.tar.gz
        blobs-directory: blobs.d

  helmcharts:
    name: Build Helmcharts
    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@master
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      name: prometheus-operator
      dir: charts/prometheus-operator
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: charts/odg
      ocm-mappings: |
        - ref: ocm-resource:prometheus-operator.repository
          attribute: image.repository
        - ref: ocm-resource:prometheus-operator.tag
          attribute: image.tag
        - ref: ocm-resource:prometheus.repository
          attribute: prometheus.image.repository
        - ref: ocm-resource:prometheus.tag
          attribute: prometheus.image.tag
        - ref: ocm-resource:prometheus-config-reloader.repository
          attribute: prometheus-config-reloader.image.repository
        - ref: ocm-resource:prometheus-config-reloader.tag
          attribute: prometheus-config-reloader.image.tag
